name: buildbot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'  # Verifica che questo sia il branch corretto

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: List files for debugging
        run: ls -la  # Verifica la presenza dei file

      - name: Build python CI
        run: |
          sudo apt-get -q update
          sudo apt-get install -y dos2unix  # Aggiungi -y per evitare conferme interattive
          pip install --upgrade pip autopep8
          ./CI/build.sh  # Verifica che questo percorso sia corretto

