name: buildbot

on:
  push:
    branches: [ pyton-3.12 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4
        with:
          ref: 'pyton-3.12'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build python CI
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8
          ./CI/build.sh
