name: Delete Artifacts

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact to delete'
        required: true

jobs:
  delete-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Artifacts
        run: |
          echo "Fetching artifacts from GitHub API..."
          artifacts=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/artifacts)
          echo "Artifacts fetched: $artifacts"
          echo "$artifacts" > artifacts.json

      - name: Parse and Delete Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifact_name="${{ github.event.inputs.artifact_name }}"
          echo "Looking for artifact: $artifact_name"
          artifact_id=$(jq -r ".artifacts[] | select(.name==\"$artifact_name\") | .id" artifacts.json)

          if [ -n "$artifact_id" ]; then
            echo "Deleting artifact ID: $artifact_id"
            gh api --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/artifacts/$artifact_id
            echo "Artifact deleted successfully."
          else
            echo "Artifact not found: $artifact_name.."
            exit 1
          fi

