name: Delete Artifacts

on:
  workflow_dispatch: # Può essere eseguita manualmente
  push:              # Oppure su push

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete old artifacts
        uses: actions/delete-artifact@v1
        with:
          name: |
            build-artifact
            another-artifact
          failOnError: true
          useGlob: true

