name: Fetch Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Fetch artifacts from GitHub API
        run: |
          echo "Fetching artifacts from GitHub API..."

          # Usa il token del repository per autenticarsi
          artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/formiano/enigma2/actions/artifacts)
          
          # Verifica se la risposta è vuota o null
          if [ -z "$artifacts" ] || [ "$artifacts" == "null" ]; then
            echo "No artifacts found."
          else
            echo "Available artifacts:"
            # Estrai e visualizza gli artefatti disponibili
            echo "$artifacts" | jq '.artifacts[] | {id: .id, name: .name, created_at: .created_at, expired: .expired}'
          fi

      - name: Collect artifacts data (optional)
        run: echo "$artifacts" >> $GITHUB_ENV

