name: all-lints


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 654wak654/python-lint@master
        with:
          python-root-list: "lib/python"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-pylint-options: ""
          extra-pycodestyle-options: "--ignore=E501,W191"
          extra-flake8-options: "--ignore=E501,W191"
          extra-black-options: "--ignore=E501,W191"
          extra-mypy-options: ""
          extra-isort-options: ""
