echo "Fetching artifacts from GitHub API..."

# Eseguiamo la richiesta API e memorizziamo la risposta
artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/formiano/enigma2/actions/artifacts)

# Mostriamo la risposta raw per il debug
echo "API response: $artifacts"

# Verifica se la risposta è vuota o null
if [ -z "$artifacts" ] || [ "$artifacts" == "null" ]; then
  echo "No artifacts found."
  echo "No artifacts found." >> $GITHUB_ENV
  echo "No artifacts found." # Output visibile nel log per chiarezza
else
  echo "Available artifacts:"
  
  # Aggiungi un controllo per vedere se la risposta contiene effettivamente un campo "artifacts"
  if echo "$artifacts" | jq -e '.artifacts' > /dev/null; then
    # Se la risposta contiene artefatti, esegui jq per estrarli
    echo "$artifacts" | jq '.artifacts[] | {id: .id, name: .name, created_at: .created_at, expired: .expired}'
  else
    echo "Artifacts key not found in the response."
    echo "Artifacts key not found in the response." >> $GITHUB_ENV
  fi

  echo "$artifacts" >> $GITHUB_ENV
fi

