name: Cleanup Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Artifacts
        run: |
          artifacts=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/${{ github.repository }}/actions/artifacts)
          echo "Artifacts: $artifacts"
          echo "$artifacts" | jq '.artifacts[] | select(.expired == false)' | while read artifact; do
            id=$(echo "$artifact" | jq -r '.id')
            echo "Deleting artifact $id"
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$id
          done

