name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Debug directory structure
      - name: Verify directory structure
        run: |
          echo "Checking project structure..."
          ls -R ./lib/python || echo "Directory ./lib/python not found"

      # Step 4: Install Ruff
      - name: Install Ruff
        run: pip install ruff

      # Step 5: Run Ruff with automatic fixes and unsafe fixes
      - name: Run Ruff (with automatic and unsafe fixes)
        run: ruff check ./lib/python/ --fix --unsafe-fixes --ignore E501,E722,F821,F405,F401,F841,E731

      # Step 6: Allow warnings without failing the job
      - name: Run Ruff (allow warnings)
        run: ruff check ./lib/python/ --ignore E501,E722,F821,F405,F401,F841,E731
        continue-on-error: true

