name: Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Debug directory structure
      - name: Verify directory structure
        run: |
          echo "Checking project structure..."
          ls -R ./lib/python/

      # Step 4: Install Ruff
      - name: Install Ruff
        run: pip install ruff

      # Step 5: Run Ruff
        run: ruff check ./lib/python/ --ignore E501,E722,F821,F405,E402,F401,E731

