name: Ruff
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: osno/ruff-action@v1
        with:
          src: "./lib/python/"
          args: --ignore E501,E722,F821,F405,E402,F401,E731
