name: updatepot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: '7.3'

      - name: updatepot
        run: |
          sudo apt-get -q update
          sudo apt-get install gettext
          git config --global user.email "bot@opendroid.com"
          git config --global user.name "opd enigma po Bot"
          git config advice.addignoredfile false
          git clean -fd
          git checkout 7.3
          cd po
          ./updatepot.sh
          cd ..
          git add -u
          git add * || :
          git commit -m "pot update"
          git remote add upstream https://${GITHUB_TOKEN}@github.com/formiano/enigma2.git > /dev/null 2>&1
          git push --quiet upstream 7.3 || echo "failed to push with error $?"
